Web API set up. Hosted- https://cryptic-basin-20296.herokuapp.com/
Darthrighteous/StackOverflow-lite pull request #2
Opened 2018-08-19 10:50 UTC by Darthrighteous

2018-08-21 19:00 UTC, Billmike requested changes

2018-08-21 19:00 UTC, Billmike commented on utils.js
> +};
New line after each object declaration.

2018-08-21 19:01 UTC, Billmike commented
1. Fix the merge conflicts you have.
2. 87 commits?? 😱

2018-08-21 23:27 UTC, Darthrighteous commented on .babelrc
> +{ "presets": ["env"] }
done

2018-08-21 23:27 UTC, Darthrighteous commented on .coveralls.yml
> +repo_token: qjtcWieTaMQEznKQOpRAIkz6xSaBFeq2Y
done

2018-08-21 23:28 UTC, Darthrighteous commented on .eslintrc
> +}
done

2018-08-21 23:28 UTC, Darthrighteous commented on .gitignore
> +/node_modules
done

2018-08-21 23:28 UTC, Darthrighteous commented on .travis.yml
> +  - npm run coverage
done

2018-08-21 23:28 UTC, Darthrighteous commented on utils.js
> +};
done

2018-08-21 23:29 UTC, Darthrighteous commented
@Billmike Thanks for the review. I think I've made all the corrections pointed out. 
Please let me know if I've miss anything!

2018-08-22 08:53 UTC, Darthrighteous commented
Added heroku link

2018-08-23 00:03 UTC, Darthrighteous commented
I have implemented es-lint rules for valid-jsdoc and max-len.

2018-09-05 05:04 UTC, closed without merging